# Generated by Django 2.0.4 on 2018-04-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('member_car_no', models.CharField(max_length=20)),
                ('member_car_model', models.CharField(max_length=20)),
                ('member_expiry_date', models.DateField()),
            ],
        ),
    ]
