# Generated by Django 2.0.4 on 2018-04-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('member_car_no', models.CharField(max_length=20)),
                ('member_car_model', models.CharField(max_length=20)),
                ('member_engine_chasis', models.CharField(max_length=20)),
                ('member_since', models.DateField()),
                ('member_tel_no', models.CharField(max_length=20)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_status', models.IntegerField()),
                ('member_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('member_expiry_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
