# Generated by Django 2.0.4 on 2018-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0003_payment_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_engine_chasis',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_expiry_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.IntegerField(blank=True),
        ),
    ]
