# Generated by Django 2.0.4 on 2018-04-20 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0004_auto_20180420_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True, default=datetime.date(2018, 4, 20)),
        ),
    ]
