# Generated by Django 2.0.4 on 2018-04-20 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0007_auto_20180420_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 20, 4, 26, 46, 622551, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 20, 4, 26, 46, 622412, tzinfo=utc)),
        ),
    ]
