# Generated by Django 2.0.4 on 2018-04-20 04:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0008_auto_20180420_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 20, 4, 28, 27, 359899, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 20, 4, 28, 27, 359749, tzinfo=utc)),
        ),
    ]
