# Generated by Django 2.0.4 on 2018-04-20 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0009_auto_20180420_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 20, 4, 29, 3, 984545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 20, 4, 29, 3, 983954, tzinfo=utc)),
        ),
    ]
