# Generated by Django 2.0.4 on 2018-04-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0010_auto_20180420_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_expiry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(auto_now=True),
        ),
    ]
