# Generated by Django 2.0.4 on 2018-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0012_auto_20180508_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='uploadreceipt'),
        ),
    ]
