# Generated by Django 2.0.4 on 2018-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0015_auto_20180515_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_on_chat',
            field=models.BooleanField(default=True),
        ),
    ]
