# Generated by Django 2.0.4 on 2018-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0016_auto_20180515_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
