# Generated by Django 2.0.4 on 2018-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0017_auto_20180515_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Car_status',
        ),
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.BooleanField(default=True),
        ),
    ]
