# Generated by Django 2.0.4 on 2018-05-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0018_auto_20180516_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_member_id',
            new_name='member_id',
        ),
    ]
