# Generated by Django 2.0.4 on 2018-05-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0019_auto_20180520_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_primary_sec',
            field=models.SmallIntegerField(choices=[('1', 'Primary'), ('2', 'Secondary')], max_length=1),
        ),
    ]
