# Generated by Django 2.0.4 on 2018-05-24 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0021_auto_20180523_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_engine_chasis',
            field=models.CharField(max_length=20, verbose_name='Engine Chassis'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=20, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_primary_sec',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Primary'), (2, 'Secondary')], null=True, verbose_name='Primary/Secondary Car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_reg_no',
            field=models.CharField(max_length=20, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_postcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_address_state',
            field=models.CharField(blank=True, choices=[('JH', 'Johor'), ('KH', 'Kedah'), ('KN', 'Kelantan'), ('KL', 'Kuala Lumpur'), ('LA', 'Labuan'), ('ME', 'Melaka'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('PK', 'Perak'), ('PL', 'Perlis'), ('PG', 'Pulau Pinang'), ('PJ', 'Putrajaya'), ('SA', 'Sabah'), ('SK', 'Sarawak'), ('SL', 'Selangor'), ('TE', 'Terengganu')], max_length=2, null=True, verbose_name='Current Location (State)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Your Birthdate'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.EmailField(max_length=200, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_on_chat',
            field=models.BooleanField(default=True, verbose_name='Would you like to be added to our WhatsApp Group?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_phone',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_source',
            field=models.CharField(blank=True, choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('SC', 'Service Center'), ('IN', 'Instagram'), ('RE', 'Referral'), ('WO', 'Word of Mouth'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Where did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_car_reg_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcmapp.Member'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_receipt_image',
            field=models.FileField(blank=True, null=True, upload_to='uploadreceipt', verbose_name='Proof of Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Renewal'), ('3', 'Supplementary')], max_length=1, verbose_name='Payment For'),
        ),
    ]
