# Generated by Django 2.0.4 on 2018-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmapp', '0022_auto_20180524_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_engine_chasis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Engine Chassis'),
        ),
    ]
